# COPY THIS EXACT CONTENT TO STREAMLIT CLOUD SECRETS
# Go to your Streamlit app → Manage app → Secrets → Paste this content

# Google Sheets Document ID
GOOGLE_SHEETS_DOC_ID = "10mBvp3OkctERgz1RaMIbOtTRKLqwuBFg"

# Google Service Account Configuration
[google_service_account]
type = "service_account"
project_id = "tf-workflow-automation"
private_key_id = "d6ed1e3d6c6d41fcb1d9d7dcd9995476f7d7067e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrirrYJQdgWMWe
WAhLCt1s4HtFcXipzPlyP3ZP8qKEQEW3/HV+mC4zZhSc8ym2ImZMi5k9xPF0pPtP
tvP3VLA5j212AsFgLDc1vhai85U77/mkOIsp5kohD1Yf0xXgo4+qR2hlvdgPX/LQ
RLBDmO5iG5vm4rbdKgakL+Ptk5e1uom5vOWOayz88AoNkWaOtfXAiU2/DRVZiM9O
2JKbbpyK1U5exllug4RtgCesuzY48M+ivgwb01AypgH7meNNs9MTSbzYF+Q936/c
pZ3RoeI2KPesLTofQxPwijmm8v/txlIp+ChLkKs3u3u+8MA+C19RNwP9c/td9Sh7
KXd6O/HpAgMBAAECggEAFYju999+KObmuCrOWmKyICRLlWYvWFxhHFSXN7t6vNDi
GmeDyzFeQMREkNzTPwgxK37YQrGMq7C30+610IuTK/FeM9MYukgSuO50zQl4kfOz
Cp4GlRX8obXZLARF2ijuX4QODme3eLFPkZHDRwPV4/8Z9/GSNKWSpoip5n4BglCv
V/afpakhl4u6l74MBFDp5bAKil0R9qiXbmWh86XRU4sI1woPeZzFu2VWpsPh+KUk
YEo2EYl5s6e7cNvLDyFpA8YlyW8zax7emjz7xWfryzNCaVZIKa0lDhMmA8bowMHv
ftMly5Bz7eCTpcYaHXewLVQNk0t9q+1oTgn+xqxLmQKBgQDXiOmt1mN1quJjipen
zkrna/VDGBESl5xol6R0OMoj1pyhvSKOOubqrGCbKW25EaxMS6R+6lCKNmbBX1Zg
rDUYvdy13vrh2M2HZtLxu7huWg309Abvp1iU+f/2Pwo1TKzSkbhsyTB8j67tS2I9
ZmJefyxdVf+t3jgAZB5Ege7xZwKBgQDLv2tdgV3Y3O8R1gjql8XTETRClfyPiKcy
aQyR7ibw2gFmmQtqAYyQtG+pAwGLHkrZgdWqnbRKu0t/p0LUCuFHBfDTn9Jd/V0I
AMyIH9ZKFpdXNhWwzJffArssru2mW9B+LmTNngUCC/97WytxHqwq1i7nZS+cSBH9
5LsE+xFgLwKBgH/GRuIrqqLjP3rLesScY4N2WNwBtH1VLABFhdTwpcVBQXIQ8h9n
g+Wzc0II+Wcxtvc0ELy8pCqLvbb9kfOVo5SbWfDn08t3/8A5kOyF4PxqnsOMt1/z
0WvgGYIeNSsL3ZinkrHLQ9dURtueSQslW0OyGNbsWLr2djSlJdxvOvwZAoGBAL02
sUCO6VaCJsrLmFA0TpTq/ztvCrNJVuxrvi6vmh5GdtKPApiZg67GwoOUtRQ7N4uz
FXhzKIHWWhDchiVhTUCl9bayT6zVpFXQWCF6X4lCXZ2yLoaYGdoTMTwX37+EuKTV
9Os2+rOh7MrkKf3NXFoTuk9OGt7p1zuP9VZ0yvglAoGATZQhmq8hjrqJQLDAPIb5
9Z9QetGSzy08RkamhvSwP5MG2PJtBz//hS0RTcmcPFTrs6jn0yPUfLXoGPtU4tmS
zfms7pEytn4dM8Gv2loczrnilotKHqfQsQ4HNyTGu3v6NczNyQRJFsTu9gIepgFN
T4L3fzKEJDCOuhmIYqmigVI=
-----END PRIVATE KEY-----"""
client_email = "tf-automation-poc@tf-workflow-automation.iam.gserviceaccount.com"
client_id = "113936139583345371141"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tf-automation-poc%40tf-workflow-automation.iam.gserviceaccount.com"
universe_domain = "googleapis.com"