# Suggested SCHEMA_MAP (paste into ingest.py or app.py and edit as needed)
SCHEMA_MAP = {
    "Sold Date": ("sold_date", "datetime64[ns]"),
    "Event Date": ("event_date", "datetime64[ns]"),
    "Time": ("time", "string"),
    "Site": ("site", "string"),
    "Order ID": ("order_id", "Int64"),
    "Confirm ID": ("confirm_id", "string"),
    "Revenue": ("revenue", "float"),
    "Cost": ("cost", "float"),
    "CNT": ("cnt", "Int64"),
    "CC": ("cc", "string"),
    "Purch By": ("purch_by", "string"),
    "Purch Date": ("purch_date", "datetime64[ns]"),
    "Trans By": ("trans_by", "string"),
    "Trans Date": ("trans_date", "datetime64[ns]"),
    "Email": ("email", "string"),
    "Event": ("event", "string"),
    "Theater": ("theater", "string"),
    "Section": ("section", "string"),
    "Row": ("row", "string"),
    "Venue": ("venue", "string"),
    "Notes": ("notes", "string"),
    "ingested_at": ("ingested_at", "datetime64[ns]"),
}
