name: Actions smoke test

on:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print environment and hello
        run: |
          echo "smoke test: Actions can run jobs"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
