name: Build and publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Create issue announcing published image
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.repo;
            const imageLatest = `ghcr.io/${repo.owner}/${repo.repo}:latest`;
            const runUrl = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${context.runId}`;
            await github.issues.create({
              owner: repo.owner,
              repo: repo.repo,
              title: `Docker image published: ${imageLatest}`,
              body: `The Docker image was built and pushed to **${imageLatest}** by workflow **${context.workflow}**.\n\nRun details: ${runUrl}`
            });
