name: Cloud Run deploy (gcloud setup minimal)

on:
  push:
    branches: [ main ]

jobs:
  gcloud-setup:
    name: gcloud setup (minimal)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI (no project)
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Show gcloud version
        run: gcloud --version

      - name: Smoke echo
        run: |
          echo "gcloud-deploy minimal: setup action ran"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
