name: Cloud Run deploy (gcloud setup)

on:
  push:
    branches: [ main ]

jobs:
  gcloud-setup:
    name: gcloud setup (incremental)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: 'latest'

      - name: Show gcloud version
        run: gcloud --version

      - name: Authenticate with service account (if provided)
        if: ${{ secrets.GCP_SA_KEY != '' }}
        run: |
          echo "Authenticating using GCP_SA_KEY secret"
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > "$RUNNER_TEMP/gcp-key.json"
          gcloud auth activate-service-account --key-file="$RUNNER_TEMP/gcp-key.json"
          gcloud config set project "${{ secrets.GCP_PROJECT }}"

      - name: List enabled APIs (no-fail)
        run: gcloud services list --enabled || true

      - name: Smoke echo
        run: |
          echo "gcloud-deploy incremental: gcloud setup complete"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
