name: Cloud Run deploy (smoke)

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "gcloud-deploy smoke: running"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
