name: Cloud Run deploy (gcloud setup minimal)

on:
  push:
    branches: [ main ]

jobs:
  gcloud-setup:
    name: gcloud setup (minimal)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI (no project)
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Show gcloud version
        run: gcloud --version

      - name: Authenticate using GCP_SA_KEY (shell)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          if [ -n "$GCP_SA_KEY" ]; then
            echo "Found GCP_SA_KEY secret, writing to temp file and activating service account"
            printf '%s' "$GCP_SA_KEY" > "$RUNNER_TEMP/gcp-key.json"
            gcloud auth activate-service-account --key-file="$RUNNER_TEMP/gcp-key.json"
            if [ -n "$GCP_PROJECT" ]; then
              gcloud config set project "$GCP_PROJECT"
            fi
            echo "Active accounts:"; gcloud auth list || true
            echo "Configured project:"; gcloud config get-value project || true
            echo "Enabled services:"; gcloud services list --enabled || true
          else
            echo "GCP_SA_KEY not provided; skipping gcloud auth"
          fi

      - name: Enable required GCP APIs (best-effort)
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          if [ -z "$GCP_PROJECT" ]; then
            echo "GCP_PROJECT not set; skipping API enable"
            exit 0
          fi
          apis=(
            "cloudresourcemanager.googleapis.com"
            "serviceusage.googleapis.com"
            "artifactregistry.googleapis.com"
            "cloudbuild.googleapis.com"
            "run.googleapis.com"
            "iam.googleapis.com"
          )
          for api in "${apis[@]}"; do
            echo "Enabling $api for project $GCP_PROJECT (best-effort)"
            gcloud services enable "$api" --project "$GCP_PROJECT" || echo "warning: failed to enable $api"
          done

      - name: Smoke echo
        run: |
          echo "gcloud-deploy minimal: setup action ran"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"

      - name: Build container with docker and push to GCR
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          repo_name=${GITHUB_REPOSITORY##*/}
          # Docker tags must be lowercase
          repo_name=${repo_name,,}
          short_sha=${GITHUB_SHA:0:8}
          IMAGE=gcr.io/${GCP_PROJECT}/${repo_name}:${short_sha}
          echo "Building and pushing image: $IMAGE"
          # Configure docker to use gcloud credential helper for GCR
          gcloud auth configure-docker --quiet
          # Build and push using Docker (avoids Cloud Build bucket permission)
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> "$GITHUB_OUTPUT"

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
          CLOUD_RUN_REGION: ${{ secrets.CLOUD_RUN_REGION }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          repo_name=${GITHUB_REPOSITORY##*/}
          # Docker tags must be lowercase
          repo_name=${repo_name,,}
          short_sha=${GITHUB_SHA:0:8}
          IMAGE=gcr.io/${GCP_PROJECT}/${repo_name}:${short_sha}
          service=${CLOUD_RUN_SERVICE:-ticketfusion}
          region=${CLOUD_RUN_REGION:-us-central1}
          echo "Deploying $IMAGE to Cloud Run service '$service' in region '$region'"
          gcloud run deploy "$service" --image "$IMAGE" --region "$region" --platform managed --quiet
          URL=$(gcloud run services describe "$service" --region "$region" --platform managed --format='value(status.url)') || URL=""
          echo "service_url=$URL" >> "$GITHUB_OUTPUT"
